apiVersion: v1
kind: Secret
metadata:
  name: shop-server-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "change_me"

  JWT_ADMIN_SECRET_KEY: "change_me"
  JWT_USER_SECRET_KEY: "change_me"

  WECHAT_SECRET: ""

  WECHAT_PAY_PRIVATE_KEY: ""
  WECHAT_PAY_API_V3_KEY: ""

  ALIOSS_ACCESSKEYID: ""
  ALIOSS_ACCESSKEYSECRET: ""
