server.port=8080
spring.profiles.active=@spring.profiles.active@

# Mapper XML
mybatis.mapper-locations=classpath:/mapper/**/*.xml
# Package path for entity classes, allowing the use of class names directly in XML.
mybatis.type-aliases-package=com.shop.entity
# Enable underscore-to-camel-case mapping, e.g. user_name -> userName
mybatis.configuration.map-underscore-to-camel-case=true

# HTTP client connection pool
http.client.max-total=200
http.client.max-per-route=50

# HTTP client timeout
http.client.connect-timeout=5s
http.client.connection-request-timeout=3s
http.client.response-timeout=10s

# Connection pool maintenance
http.client.validate-after-inactivity=5s
http.client.idle-connection-evict-time=30s
