server.port=8080
spring.profiles.active=@spring.profiles.active@

# Mapper XML
mybatis.mapper-locations=classpath:/mapper/**/*.xml
# Package path for entity classes, allowing the use of class names directly in XML.
mybatis.type-aliases-package=com.shop.entity
# Enable underscore-to-camel-case mapping, e.g. user_name -> userName
mybatis.configuration.map-underscore-to-camel-case=true

